name: vajaah
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9936673785559833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f8'
    - '#2b2c27'
    - '#5c5d57'
    - '#afb3b2'
    - '#fec05a'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
